class DrugInteractionChecker:
    def __init__(self):
        self.interactions = {
            ("Aspirin", "Warfarin"): "Aspirin increases the effects of Warfarin and may increase the risk of bleeding or bruising.",
            ("Aspirin", "Ibuprofen"): "Taking Aspirin with Ibuprofen can increase the risk of stomach bleeding.",
            ("Warfarin", "Aspirin"): "Aspirin increases the effects of Warfarin and may increase the risk of bleeding or bruising.",
            ("Lorazepam", "Alcohol"): "Avoid alcohol while taking Lorazepam as it can increase drowsiness and dizziness.",
            ("Ibuprofen", "Aspirin"): "Taking Ibuprofen with Aspirin can increase the risk of stomach bleeding.",
            ("Ibuprofen", "Lisinopril"): "Ibuprofen can reduce the effectiveness of Lisinopril in lowering blood pressure.",
            ("Lisinopril", "Ibuprofen"): "Ibuprofen can reduce the effectiveness of Lisinopril in lowering blood pressure.",
            ("Metformin", "Lisinopril"): "Lisinopril can increase blood sugar levels when taken with Metformin.",
            ("Lisinopril", "Metformin"): "Lisinopril can increase blood sugar levels when taken with Metformin.",
            ("Metformin", "Simvastatin"): "Metformin can reduce the effectiveness of Simvastatin in lowering cholesterol.",
            ("Simvastatin", "Metformin"): "Metformin can reduce the effectiveness of Simvastatin in lowering cholesterol.",
            ("Simvastatin", "Clopidogrel"): "Simvastatin may increase the risk of muscle breakdown when taken with Clopidogrel.",
            ("Clopidogrel", "Simvastatin"): "Simvastatin may increase the risk of muscle breakdown when taken with Clopidogrel.",
            ("Clopidogrel", "Pantoprazole"): "Clopidogrel's effectiveness may be reduced when taken with Pantoprazole.",
            ("Pantoprazole", "Clopidogrel"): "Clopidogrel's effectiveness may be reduced when taken with Pantoprazole.",
            ("Pantoprazole", "Digoxin"): "Pantoprazole may increase Digoxin levels in the blood, leading to toxicity.",
            ("Digoxin", "Pantoprazole"): "Pantoprazole may increase Digoxin levels in the blood, leading to toxicity.",
            ("Digoxin", "Furosemide"): "Digoxin and Furosemide can cause an increased risk of low blood potassium levels.",
            ("Furosemide", "Digoxin"): "Digoxin and Furosemide can cause an increased risk of low blood potassium levels.",
            ("Furosemide", "Metoprolol"): "Furosemide and Metoprolol can lower blood pressure and heart rate when taken together.",
            ("Metoprolol", "Furosemide"): "Furosemide and Metoprolol can lower blood pressure and heart rate when taken together.",
            ("Metoprolol", "Omeprazole"): "Metoprolol's effectiveness may be reduced when taken with Omeprazole.",
            ("Omeprazole", "Metoprolol"): "Metoprolol's effectiveness may be reduced when taken with Omeprazole.",
            ("Omeprazole", "Atorvastatin"): "Omeprazole can reduce the absorption of Atorvastatin in the body, reducing its effectiveness.",
            ("Atorvastatin", "Omeprazole"): "Omeprazole can reduce the absorption of Atorvastatin in the body, reducing its effectiveness.",
            ("Atorvastatin", "Diltiazem"): "Atorvastatin and Diltiazem together can increase the risk of muscle breakdown.",
            ("Diltiazem", "Atorvastatin"): "Atorvastatin and Diltiazem together can increase the risk of muscle breakdown.",
            ("Diltiazem", "Rivaroxaban"): "Diltiazem can increase Rivaroxaban levels in the blood, increasing the risk of bleeding.",
            ("Rivaroxaban", "Diltiazem"): "Diltiazem can increase Rivaroxaban levels in the blood, increasing the risk of bleeding.",
            ("Rivaroxaban", "Gabapentin"): "Rivaroxaban can increase the risk of bleeding when taken with Gabapentin.",
            ("Gabapentin", "Rivaroxaban"): "Rivaroxaban can increase the risk of bleeding when taken with Gabapentin.",
            ("Gabapentin", "Levothyroxine"): "Gabapentin may reduce Levothyroxine absorption when taken together.",
            ("Levothyroxine", "Gabapentin"): "Gabapentin may reduce Levothyroxine absorption when taken together.",
            ("Levothyroxine", "Prednisone"): "Levothyroxine levels in the blood may decrease when taken with Prednisone.",
            ("Prednisone", "Levothyroxine"): "Levothyroxine levels in the blood may decrease when taken with Prednisone.",
            ("Prednisone", "Sertraline"): "Prednisone and Sertraline can increase the risk of low sodium levels in the blood.",
            ("Sertraline", "Prednisone"): "Prednisone and Sertraline can increase the risk of low sodium levels in the blood.",
            ("Sertraline", "Venlafaxine"): "Sertraline and Venlafaxine together can increase the risk of serotonin syndrome.",
            ("Venlafaxine", "Sertraline"): "Sertraline and Venlafaxine together can increase the risk of serotonin syndrome.",
            ("Venlafaxine", "Quetiapine"): "Venlafaxine can increase Quetiapine levels in the blood, leading to increased side effects.",
            ("Quetiapine", "Venlafaxine"): "Venlafaxine can increase Quetiapine levels in the blood, leading to increased side effects.",
            ("Quetiapine", "Escitalopram"): "Quetiapine and Escitalopram together can increase the risk of heart rhythm problems.",
            ("Escitalopram", "Quetiapine"): "Quetiapine and Escitalopram together can increase the risk of heart rhythm problems.",
            ("Escitalopram", "Tramadol"): "Escitalopram can increase Tramadol levels in the blood, increasing the risk of seizures.",
            ("Tramadol", "Escitalopram"): "Escitalopram can increase Tramadol levels in the blood, increasing the risk of seizures.",
            ("Tramadol", "Hydrocodone"): "Tramadol and Hydrocodone together can increase the risk of respiratory depression.",
            ("Hydrocodone", "Tramadol"): "Tramadol and Hydrocodone together can increase the risk of respiratory depression.",
            ("Hydrocodone", "Morphine"): "Hydrocodone can increase Morphine levels in the blood, increasing the risk of side effects.",
            ("Morphine", "Hydrocodone"): "Hydrocodone can increase Morphine levels in the blood, increasing the risk of side effects.",
            ("Morphine", "Codeine"): "Morphine and Codeine together can increase the risk of respiratory depression.",
            ("Codeine", "Morphine"): "Morphine and Codeine together can increase the risk of respiratory depression.",
            ("Codeine", "Alprazolam"): "Codeine can increase Alprazolam levels in the blood, leading to increased sedation.",
            ("Alprazolam", "Codeine"): "Codeine can increase Alprazolam levels in the blood, leading to increased sedation.",
            ("Alprazolam", "Citalopram"): "Alprazolam and Citalopram together can increase the risk of drowsiness and confusion.",
            ("Citalopram", "Alprazolam"): "Alprazolam and Citalopram together can increase the risk of drowsiness and confusion.",
            ("Citalopram", "Zolpidem"): "Citalopram can increase Zolpidem levels in the blood, leading to increased sedation.",
            ("Zolpidem", "Citalopram"): "Citalopram can increase Zolpidem levels in the blood, leading to increased sedation.",
            ("Zolpidem", "Diazepam"): "Zolpidem and Diazepam together can increase the risk of drowsiness and respiratory depression.",
            ("Diazepam", "Zolpidem"): "Zolpidem and Diazepam together can increase the risk of drowsiness and respiratory depression.",
            ("Diazepam",
             "Clonazepam"): "Diazepam can increase Clonazepam levels in the blood, leading to increased sedation.",
            ("Clonazepam",
             "Diazepam"): "Diazepam can increase Clonazepam levels in the blood, leading to increased sedation.",
            ("Clonazepam", "Bupropion"): "Clonazepam and Bupropion together can increase the risk of seizures.",
            ("Bupropion", "Clonazepam"): "Clonazepam and Bupropion together can increase the risk of seizures.",
            ("Bupropion",
             "Amitriptyline"): "Bupropion can increase Amitriptyline levels in the blood, leading to increased side effects.",
            ("Amitriptyline",
             "Bupropion"): "Bupropion can increase Amitriptyline levels in the blood, leading to increased side effects.",
            ("Amitriptyline",
             "Trazodone"): "Amitriptyline and Trazodone together can increase the risk of serotonin syndrome.",
            ("Trazodone",
             "Amitriptyline"): "Amitriptyline and Trazodone together can increase the risk of serotonin syndrome.",
            ("Trazodone",
             "Cyclobenzaprine"): "Trazodone can increase Cyclobenzaprine levels in the blood, leading to increased sedation.",
            ("Cyclobenzaprine",
             "Trazodone"): "Trazodone can increase Cyclobenzaprine levels in the blood, leading to increased sedation.",
            ("Cyclobenzaprine",
             "Hydroxyzine"): "Cyclobenzaprine and Hydroxyzine together can increase the risk of drowsiness and confusion.",
            ("Hydroxyzine",
             "Cyclobenzaprine"): "Cyclobenzaprine and Hydroxyzine together can increase the risk of drowsiness and confusion.",
            ("Hydroxyzine",
             "Diphenhydramine"): "Hydroxyzine can increase Diphenhydramine levels in the blood, leading to increased sedation.",
            ("Diphenhydramine",
             "Hydroxyzine"): "Hydroxyzine can increase Diphenhydramine levels in the blood, leading to increased sedation.",
            ("Diphenhydramine",
             "Loratadine"): "Diphenhydramine and Loratadine together can increase the risk of drowsiness and confusion.",
            ("Loratadine",
             "Diphenhydramine"): "Diphenhydramine and Loratadine together can increase the risk of drowsiness and confusion.",
            ("Loratadine",
             "Cetirizine"): "Loratadine can increase Cetirizine levels in the blood, leading to increased sedation.",
            ("Cetirizine",
             "Loratadine"): "Loratadine can increase Cetirizine levels in the blood, leading to increased sedation.",
            ("Cetirizine",
             "Montelukast"): "Cetirizine and Montelukast together can increase the risk of mood changes and behavioral problems.",
            ("Montelukast",
             "Cetirizine"): "Cetirizine and Montelukast together can increase the risk of mood changes and behavioral problems.",
            ("Montelukast",
             "Esomeprazole"): "Montelukast levels in the blood can increase when taken with Esomeprazole, leading to increased side effects.",
            ("Esomeprazole",
             "Montelukast"): "Montelukast levels in the blood can increase when taken with Esomeprazole, leading to increased side effects.",
            ("Esomeprazole",
             "Lansoprazole"): "Esomeprazole and Lansoprazole together can decrease the absorption of some drugs.",
            ("Lansoprazole",
             "Esomeprazole"): "Esomeprazole and Lansoprazole together can decrease the absorption of some drugs.",
            ("Lansoprazole",
             "Ranitidine"): "Lansoprazole can increase Ranitidine levels in the blood, leading to increased side effects.",
            ("Ranitidine",
             "Lansoprazole"): "Lansoprazole can increase Ranitidine levels in the blood, leading to increased side effects.",
            ("Ranitidine",
             "Famotidine"): "Ranitidine and Famotidine together can increase the risk of confusion and dizziness.",
            ("Famotidine",
             "Ranitidine"): "Ranitidine and Famotidine together can increase the risk of confusion and dizziness.",
            ("Famotidine",
             "Ondansetron"): "Famotidine can increase Ondansetron levels in the blood, leading to increased side effects.",
            ("Ondansetron",
             "Famotidine"): "Famotidine can increase Ondansetron levels in the blood, leading to increased side effects.",
            ("Ondansetron",
             "Metoclopramide"): "Ondansetron and Metoclopramide together can increase the risk of heart rhythm problems.",
            ("Metoclopramide",
             "Ondansetron"): "Ondansetron and Metoclopramide together can increase the risk of heart rhythm problems.",
            ("Metoclopramide",
             "Risperidone"): "Metoclopramide can increase Risperidone levels in the blood, leading to increased side effects.",
            ("Risperidone",
             "Metoclopramide"): "Metoclopramide can increase Risperidone levels in the blood, leading to increased side effects.",
            ("Risperidone",
             "Haloperidol"): "Risperidone and Haloperidol together can increase the risk of muscle stiffness and tremors.",
            ("Haloperidol",
             "Risperidone"): "Risperidone and Haloperidol together can increase the risk of muscle stiffness and tremors.",
            ("Haloperidol",
             "Lithium"): "Haloperidol can increase Lithium levels in the blood, leading to increased side effects.",
            ("Lithium",
             "Haloperidol"): "Haloperidol can increase Lithium levels in the blood, leading to increased side effects.",
            ("Lithium",
             "Valproic Acid"): "Lithium and Valproic Acid together can increase the risk of drowsiness and dizziness.",
            ("Valproic Acid",
             "Lithium"): "Lithium and Valproic Acid together can increase the risk of drowsiness and dizziness.",
            ("Valproic Acid",
             "Carbamazepine"): "Valproic Acid can increase Carbamazepine levels in the blood, leading to increased side effects.",
            ("Carbamazepine",
             "Valproic Acid"): "Valproic Acid can increase Carbamazepine levels in the blood, leading to increased side effects.",
            ("Carbamazepine", "Phenytoin"): "Carbamazepine and Phenytoin together can increase the risk of seizures.",
            ("Phenytoin", "Carbamazepine"): "Carbamazepine and Phenytoin together can increase the risk of seizures.",
            ("Phenytoin",
             "Lamotrigine"): "Phenytoin can decrease Lamotrigine levels in the blood, reducing its effectiveness.",
            ("Lamotrigine",
             "Phenytoin"): "Phenytoin can decrease Lamotrigine levels in the blood, reducing its effectiveness.",
            ("Lamotrigine",
             "Topiramate"): "Lamotrigine and Topiramate together can increase the risk of blurred vision and difficulty concentrating.",
            ("Topiramate",
             "Lamotrigine"): "Lamotrigine and Topiramate together can increase the risk of blurred vision and difficulty concentrating.",
            ("Topiramate",
             "Divalproex Sodium"): "Topiramate can increase Divalproex Sodium levels in the blood, leading to increased side effects.",
            ("Divalproex Sodium",
             "Topiramate"): "Topiramate can increase Divalproex Sodium levels in the blood, leading to increased side effects.",
            ("Divalproex Sodium",
             "Levetiracetam"): "Divalproex Sodium and Levetiracetam together can increase the risk of mood changes and behavioral problems.",
            ("Levetiracetam",
             "Divalproex Sodium"): "Divalproex Sodium and Levetiracetam together can increase the risk of mood changes and behavioral problems.",
            ("Levetiracetam",
             "Gabapentin"): "Levetiracetam can increase Gabapentin levels in the blood, leading to increased side effects.",
            ("Gabapentin",
             "Levetiracetam"): "Levetiracetam can increase Gabapentin levels in the blood, leading to increased side effects.",
            ("Warfarin", "Clopidogrel"): "Warfarin and Clopidogrel together can increase the risk of bleeding.",
            ("Clopidogrel", "Warfarin"): "Warfarin and Clopidogrel together can increase the risk of bleeding.",
            ("Clopidogrel", "Omeprazole"): "Clopidogrel's effectiveness may be reduced when taken with Omeprazole.",
            ("Omeprazole", "Clopidogrel"): "Clopidogrel's effectiveness may be reduced when taken with Omeprazole.",
            ("Omeprazole",
             "Diazepam"): "Omeprazole can increase Diazepam levels in the blood, leading to increased sedation.",
            ("Diazepam",
             "Omeprazole"): "Omeprazole can increase Diazepam levels in the blood, leading to increased sedation.",
            ("Diazepam",
             "Phenytoin"): "Diazepam can increase Phenytoin levels in the blood, leading to increased sedation.",
            ("Phenytoin",
             "Diazepam"): "Diazepam can increase Phenytoin levels in the blood, leading to increased sedation.",
            ("Phenytoin", "Furosemide"): "Phenytoin can reduce the effectiveness of Furosemide in treating seizures.",
            ("Furosemide", "Phenytoin"): "Phenytoin can reduce the effectiveness of Furosemide in treating seizures.",
            ("Furosemide", "Metformin"): "Furosemide can increase blood sugar levels when taken with Metformin.",
            ("Metformin", "Furosemide"): "Furosemide can increase blood sugar levels when taken with Metformin.",
            ("Metformin",
             "Atorvastatin"): "Metformin can reduce the effectiveness of Atorvastatin in lowering cholesterol.",
            ("Atorvastatin",
             "Metformin"): "Metformin can reduce the effectiveness of Atorvastatin in lowering cholesterol.",
            ("Atorvastatin",
             "Sertraline"): "Atorvastatin may increase Sertraline levels in the blood, leading to increased side effects.",
            ("Sertraline",
             "Atorvastatin"): "Atorvastatin may increase Sertraline levels in the blood, leading to increased side effects.",
            ("Sertraline",
             "Morphine"): "Sertraline can increase Morphine levels in the blood, leading to increased sedation.",
            ("Morphine",
             "Sertraline"): "Sertraline can increase Morphine levels in the blood, leading to increased sedation.",
            ("Morphine",
             "Citalopram"): "Morphine and Citalopram together can increase the risk of respiratory depression.",
            ("Citalopram",
             "Morphine"): "Morphine and Citalopram together can increase the risk of respiratory depression.",
            ("Citalopram",
             "Gabapentin"): "Citalopram can increase Gabapentin levels in the blood, leading to increased side effects.",
            ("Gabapentin",
             "Citalopram"): "Citalopram can increase Gabapentin levels in the blood, leading to increased side effects.",
            ("Gabapentin",
             "Lisinopril"): "Gabapentin may reduce the effectiveness of Lisinopril in lowering blood pressure.",
            ("Lisinopril",
             "Gabapentin"): "Gabapentin may reduce the effectiveness of Lisinopril in lowering blood pressure.",
            ("Lisinopril",
             "Amitriptyline"): "Lisinopril can increase Amitriptyline levels in the blood, leading to increased side effects.",
            ("Amitriptyline",
             "Lisinopril"): "Lisinopril can increase Amitriptyline levels in the blood, leading to increased side effects.",
            ("Amitriptyline",
             "Warfarin"): "Amitriptyline can increase the effects of Warfarin, increasing the risk of bleeding.",
            ("Warfarin",
             "Amitriptyline"): "Amitriptyline can increase the effects of Warfarin, increasing the risk of bleeding.",
            ("Warfarin",
             "Metoprolol"): "Warfarin can reduce the effectiveness of Metoprolol in controlling heart rate and blood pressure.",
            ("Metoprolol",
             "Warfarin"): "Warfarin can reduce the effectiveness of Metoprolol in controlling heart rate and blood pressure.",
            ("Metoprolol",
             "Hydrochlorothiazide"): "Metoprolol and Hydrochlorothiazide together can lower blood pressure excessively.",
            ("Hydrochlorothiazide",
             "Metoprolol"): "Metoprolol and Hydrochlorothiazide together can lower blood pressure excessively.",
            ("Hydrochlorothiazide",
             "Escitalopram"): "Hydrochlorothiazide can reduce Escitalopram levels in the blood, reducing its effectiveness.",
            ("Escitalopram",
             "Hydrochlorothiazide"): "Hydrochlorothiazide can reduce Escitalopram levels in the blood, reducing its effectiveness.",
            ("Escitalopram",
             "Ondansetron"): "Escitalopram can increase Ondansetron levels in the blood, leading to increased side effects.",
            ("Ondansetron",
             "Escitalopram"): "Escitalopram can increase Ondansetron levels in the blood, leading to increased side effects.",
            ("Ondansetron",
             "Digoxin"): "Ondansetron can increase Digoxin levels in the blood, leading to increased side effects.",
            ("Digoxin",
             "Ondansetron"): "Ondansetron can increase Digoxin levels in the blood, leading to increased side effects.",
            ("Digoxin", "Carbamazepine"): "Digoxin levels in the blood may decrease when taken with Carbamazepine.",
            ("Carbamazepine", "Digoxin"): "Digoxin levels in the blood may decrease when taken with Carbamazepine.",
            ("Carbamazepine",
             "Levothyroxine"): "Carbamazepine can reduce Levothyroxine levels in the blood, reducing its effectiveness.",
            ("Levothyroxine",
             "Carbamazepine"): "Carbamazepine can reduce Levothyroxine levels in the blood, reducing its effectiveness.",
            ("Levothyroxine",
             "Lorazepam"): "Levothyroxine can increase Lorazepam levels in the blood, leading to increased sedation.",
            ("Lorazepam",
             "Levothyroxine"): "Levothyroxine can increase Lorazepam levels in the blood, leading to increased sedation.",
            ("Lorazepam",
             "Quetiapine"): "Lorazepam can increase Quetiapine levels in the blood, leading to increased sedation.",
            ("Quetiapine",
             "Lorazepam"): "Lorazepam can increase Quetiapine levels in the blood, leading to increased sedation.",
            ("Quetiapine",
             "Zolpidem"): "Quetiapine can increase Zolpidem levels in the blood, leading to increased sedation.",
            ("Zolpidem",
             "Quetiapine"): "Quetiapine can increase Zolpidem levels in the blood, leading to increased sedation.",
            ("Zolpidem",
             "Metoclopramide"): "Zolpidem can increase Metoclopramide levels in the blood, leading to increased sedation.",
            ("Metoclopramide",
             "Zolpidem"): "Zolpidem can increase Metoclopramide levels in the blood, leading to increased sedation.",
            ("Metoclopramide",
             "Pantoprazole"): "Metoclopramide can reduce Pantoprazole levels in the blood, reducing its effectiveness.",
            ("Pantoprazole",
             "Metoclopramide"): "Metoclopramide can reduce Pantoprazole levels in the blood, reducing its effectiveness.",
            ("Pantoprazole",
             "Risperidone"): "Pantoprazole can increase Risperidone levels in the blood, leading to increased side effects.",
            ("Risperidone",
             "Pantoprazole"): "Pantoprazole can increase Risperidone levels in the blood, leading to increased side effects.",
            ("Risperidone",
             "Hydroxyzine"): "Risperidone can increase Hydroxyzine levels in the blood, leading to increased sedation.",
            ("Hydroxyzine",
             "Risperidone"): "Risperidone can increase Hydroxyzine levels in the blood, leading to increased sedation.",
            ("Hydroxyzine",
             "Loratadine"): "Hydroxyzine can increase Loratadine levels in the blood, leading to increased sedation.",
            ("Loratadine",
             "Hydroxyzine"): "Hydroxyzine can increase Loratadine levels in the blood, leading to increased sedation.",
            ("Loratadine",
             "Cetirizine"): "Loratadine and Cetirizine together can increase the risk of drowsiness and confusion.",
            ("Cetirizine",
             "Montelukast"): "Cetirizine can increase Montelukast levels in the blood, leading to increased sedation.",
            ("Montelukast",
             "Cetirizine"): "Cetirizine can increase Montelukast levels in the blood, leading to increased sedation.",
            ("Montelukast",
             "Esomeprazole"): "Montelukast can reduce Esomeprazole levels in the blood, reducing its effectiveness.",
            ("Esomeprazole",
             "Montelukast"): "Montelukast can reduce Esomeprazole levels in the blood, reducing its effectiveness.",
            ("Esomeprazole",
             "Lansoprazole"): "Esomeprazole can increase Lansoprazole levels in the blood, leading to increased side effects.",
            ("Lansoprazole",
             "Esomeprazole"): "Esomeprazole can increase Lansoprazole levels in the blood, leading to increased side effects.",
            ("Lansoprazole",
             "Ranitidine"): "Lansoprazole can reduce Ranitidine levels in the blood, reducing its effectiveness.",
            ("Ranitidine",
             "Lansoprazole"): "Lansoprazole can reduce Ranitidine levels in the blood, reducing its effectiveness.",
            ("Ranitidine",
             "Famotidine"): "Ranitidine can increase Famotidine levels in the blood, leading to increased side effects.",
            ("Famotidine",
             "Ranitidine"): "Ranitidine can increase Famotidine levels in the blood, leading to increased side effects.",
            ("Famotidine",
             "Ondansetron"): "Famotidine can increase Ondansetron levels in the blood, leading to increased side effects.",
            ("Ondansetron",
             "Famotidine"): "Famotidine can increase Ondansetron levels in the blood, leading to increased side effects.",
            ("Ondansetron",
             "Metoclopramide"): "Ondansetron can reduce Metoclopramide levels in the blood, reducing its effectiveness.",
            ("Metoclopramide",
             "Ondansetron"): "Ondansetron can reduce Metoclopramide levels in the blood, reducing its effectiveness.",
            ("Metoclopramide",
             "Risperidone"): "Metoclopramide can increase Risperidone levels in the blood, leading to increased side effects.",
            ("Risperidone",
             "Metoclopramide"): "Metoclopramide can increase Risperidone levels in the blood, leading to increased side effects.",
            ("Risperidone",
             "Haloperidol"): "Risperidone can increase Haloperidol levels in the blood, leading to increased side effects.",
            ("Haloperidol",
             "Risperidone"): "Risperidone can increase Haloperidol levels in the blood, leading to increased side effects.",
            ("Haloperidol",
             "Lithium"): "Haloperidol can increase Lithium levels in the blood, leading to increased side effects.",
            ("Lithium",
             "Haloperidol"): "Haloperidol can increase Lithium levels in the blood, leading to increased side effects.",
            ("Lithium",
             "Valproic Acid"): "Lithium can increase Valproic Acid levels in the blood, leading to increased side effects.",
            ("Valproic Acid",
             "Lithium"): "Lithium can increase Valproic Acid levels in the blood, leading to increased side effects.",
            ("Valproic Acid",
             "Carbamazepine"): "Valproic Acid can reduce Carbamazepine levels in the blood, reducing its effectiveness.",
            ("Carbamazepine",
             "Valproic Acid"): "Valproic Acid can reduce Carbamazepine levels in the blood, reducing its effectiveness.",
            ("Carbamazepine", "Phenytoin"): "Carbamazepine and Phenytoin together can increase the risk of seizures.",
            ("Phenytoin", "Carbamazepine"): "Carbamazepine and Phenytoin together can increase the risk of seizures.",
            ("Phenytoin",
             "Lamotrigine"): "Phenytoin can reduce Lamotrigine levels in the blood, reducing its effectiveness.",
            ("Lamotrigine",
             "Phenytoin"): "Phenytoin can reduce Lamotrigine levels in the blood, reducing its effectiveness.",
            ("Lamotrigine",
             "Topiramate"): "Lamotrigine can increase Topiramate levels in the blood, leading to increased side effects.",
            ("Topiramate",
             "Lamotrigine"): "Lamotrigine can increase Topiramate levels in the blood, leading to increased side effects.",
            ("Topiramate",
             "Divalproex Sodium"): "Topiramate can reduce Divalproex Sodium levels in the blood, reducing its effectiveness.",
            ("Divalproex Sodium",
             "Topiramate"): "Topiramate can reduce Divalproex Sodium levels in the blood, reducing its effectiveness.",
            ("Divalproex Sodium",
             "Levetiracetam"): "Divalproex Sodium can reduce Levetiracetam levels in the blood, reducing its effectiveness.",
            ("Levetiracetam",
             "Divalproex Sodium"): "Divalproex Sodium can reduce Levetiracetam levels in the blood, reducing its effectiveness.",
            ("Levetiracetam",
             "Gabapentin"): "Levetiracetam can reduce Gabapentin levels in the blood, reducing its effectiveness.",
            ("Gabapentin",
             "Levetiracetam"): "Levetiracetam can reduce Gabapentin levels in the blood, reducing its effectiveness."

        }
        self.drug_names = list(set([drug for interaction in self.interactions for drug in interaction]))

    def check_interaction(self, drug1, drug2):
        # Check if drugs are in the known drug list
        if drug1 not in self.drug_names:
            return f"{drug1} is not recognized."

        if drug2 not in self.drug_names:
            return f"{drug2} is not recognized."

        # Check if both drugs are in the interactions dictionary
        interaction_key = (drug1, drug2)
        if interaction_key in self.interactions:
            return self.interactions[interaction_key]

        # Check the reverse order of drugs
        interaction_key_reverse = (drug2, drug1)
        if interaction_key_reverse in self.interactions:
            return self.interactions[interaction_key_reverse]

        # If no interaction found in either direction
        return "No known interaction found."